#!/bin/bash
# VDBRender — Linux build script (RHEL 9 family: Rocky/Alma; other distros
# should work with equivalent packages).
#
# Builds VDBRender.so for every Nuke installation found under /usr/local
# that ships oneTBB (Nuke 17+; older Nukes bundle pre-oneTBB and are skipped).
# Links against Nuke's own bundled libopenvdb/libtbb, so the only things
# fetched are matching HEADERS (into .deps/, first run only).
#
# Prerequisites:
#   sudo dnf install -y cmake gcc-c++ git imath-devel
#
# Usage:
#   ./build_linux.sh                # build for all detected Nukes, install to ~/.nuke/plugins
#   DEST=/path ./build_linux.sh     # override install location
#   OPENVDB_HEADERS=... ONETBB_HEADERS=... ./build_linux.sh   # use existing header checkouts
#
# Linux port by Soup Kitchen Films (https://github.com/soupkitchenfilms),
# developed with the assistance of Claude (Anthropic).
# Original plugin by Marten Blumen — https://github.com/bratgot/VDBmarcher (MIT).
# See LINUX_BUILD.md for background and troubleshooting.

set -euo pipefail

SRC="$(cd "$(dirname "$0")" && pwd)"
DEPS="${SRC}/.deps"
DEST="${DEST:-$HOME/.nuke/plugins/VDBRender}"

# Header versions — must match the libraries Nuke bundles.
# Nuke 17 ships libopenvdb.so.12.0 and libtbb.so.12.13 (oneTBB 2021.13).
OPENVDB_TAG="v12.0.0"
ONETBB_TAG="v2021.13.0"

OPENVDB_HEADERS="${OPENVDB_HEADERS:-${DEPS}/openvdb/openvdb}"
ONETBB_HEADERS="${ONETBB_HEADERS:-${DEPS}/oneTBB/include}"

echo ""
echo "  VDBRender Linux Builder"
echo ""

# ── Fetch header dependencies (first run only) ────────────────────────────────
fetch_deps() {
    mkdir -p "$DEPS"
    if [ ! -d "${DEPS}/openvdb" ] && [ ! -f "${OPENVDB_HEADERS}/openvdb/openvdb.h" ]; then
        echo "  FETCH OpenVDB ${OPENVDB_TAG} headers"
        git clone --quiet --depth 1 --branch "$OPENVDB_TAG" \
            https://github.com/AcademySoftwareFoundation/openvdb "${DEPS}/openvdb"
    fi
    if [ ! -d "${DEPS}/oneTBB" ] && [ ! -f "${ONETBB_HEADERS}/tbb/tbb.h" ]; then
        echo "  FETCH oneTBB ${ONETBB_TAG} headers"
        git clone --quiet --depth 1 --branch "$ONETBB_TAG" \
            https://github.com/uxlfoundation/oneTBB "${DEPS}/oneTBB"
    fi

    # OpenVDB's version.h is normally generated by its own CMake configure.
    # For a header-only consumer build (we link Nuke's pre-built libopenvdb)
    # we install a pre-generated copy with OPENVDB_USE_EXPLICIT_INSTANTIATION
    # disabled — leaving it enabled would emit "extern template" references to
    # symbols only present in a full OpenVDB build. See linux/openvdb_version.h.
    local VH="${OPENVDB_HEADERS}/openvdb/version.h"
    if [ ! -f "$VH" ]; then
        echo "  INSTALL pre-generated openvdb/version.h (header-only consumer, ABI 12)"
        cp "${SRC}/linux/openvdb_version.h" "$VH"
    fi
}

fetch_deps

# ── Build per Nuke install ────────────────────────────────────────────────────
N=0
SEEN=""
build_for_nuke() {
    # Resolve symlinks (e.g. /usr/local/Nuke -> Nuke17.0v3) and build each
    # real install once.
    local NUKE_DIR
    NUKE_DIR="$(readlink -f "${1%/}")"
    case " $SEEN " in *" $NUKE_DIR "*) return ;; esac
    SEEN="$SEEN $NUKE_DIR"
    local NUKE_NAME
    NUKE_NAME="$(basename "$NUKE_DIR")"

    if [ ! -f "${NUKE_DIR}/include/DDImage/Iop.h" ]; then
        echo "  SKIP ${NUKE_NAME} [no NDK headers]"
        return
    fi
    # Nuke 17+ ships oneTBB (libtbb.so.12); earlier Nukes bundle a TBB whose
    # API predates oneTBB and will not match the oneTBB headers we compile with.
    if [ ! -f "${NUKE_DIR}/libtbb.so.12" ] && [ ! -f "${NUKE_DIR}/libtbb.so" ]; then
        echo "  SKIP ${NUKE_NAME} [no oneTBB — Nuke 17+ required]"
        return
    fi

    local MAJOR
    MAJOR=$(echo "$NUKE_NAME" | sed 's/Nuke\([0-9]*\).*/\1/')

    echo "  BUILD ${NUKE_NAME}"
    local BD="${SRC}/build_linux_nuke${MAJOR}"
    cmake -S "${SRC}/linux" -B "$BD" \
        -DCMAKE_BUILD_TYPE=Release \
        -DNUKE_ROOT="$NUKE_DIR" \
        -DOPENVDB_HEADER_DIR="$OPENVDB_HEADERS" \
        -DONETBB_HEADER_DIR="$ONETBB_HEADERS" \
        -DCMAKE_INSTALL_PREFIX="${DEST}/nuke${MAJOR}" \
        2>&1 | sed 's/^/    /'
    cmake --build "$BD" --parallel 2>&1 | tail -3 | sed 's/^/    /'

    if [ -f "${BD}/VDBRender.so" ]; then
        mkdir -p "${DEST}/nuke${MAJOR}"
        cp -v "${BD}/VDBRender.so" "${DEST}/nuke${MAJOR}/" | sed 's/^/    /'
        echo "  OK ${NUKE_NAME}"
        N=$((N + 1))
    else
        echo "  FAIL ${NUKE_NAME}"
    fi
}

for NUKE_DIR in /usr/local/Nuke*/; do
    [ -d "$NUKE_DIR" ] && build_for_nuke "$NUKE_DIR"
done

# ── Menu registration (opt-in: INSTALL_MENU=1) ────────────────────────────────
MENUPY="$HOME/.nuke/menu.py"
if [ "$N" -gt 0 ]; then
    if [ "${INSTALL_MENU:-0}" = "1" ] && [ -f "${SRC}/VDBRender_menu.py" ]; then
        if ! grep -q "_load_vdbrender" "$MENUPY" 2>/dev/null; then
            { echo ""; cat "${SRC}/VDBRender_menu.py"; } >> "$MENUPY"
            echo "  Menu block appended to ${MENUPY}"
        fi
    else
        echo "  To register the node menu, append VDBRender_menu.py to your"
        echo "  ~/.nuke/menu.py (or re-run with INSTALL_MENU=1)."
    fi
fi

echo ""
echo "  Built ${N} version(s) to ${DEST}"
echo ""
